name: Generate Keystore
on: workflow_dispatch
jobs:
  create-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore focus.keystore -alias focus -keyalg RSA -keysize 2048 -validity 10000 -storepass 1234546996562154756 -keypass 1234546996562154756 -dname "CN=Focus Flow, OU=Dev, O=Focus, L=City, S=State, C=US"
          base64 -w 0 focus.keystore > keystore_base64.txt

      - name: Upload Keystore Files
        uses: actions/upload-artifact@v4
        with:
          name: Keystore-Artifacts
          path: |
            focus.keystore
            keystore_base64.txt